package ru.glassspirit.conquest.block

import com.teamwizardry.librarianlib.features.base.block.BlockMod
import com.teamwizardry.librarianlib.features.base.block.BlockModPillar
import com.teamwizardry.librarianlib.features.base.block.BlockModPlanks
import net.minecraft.block.material.Material
import ru.glassspirit.conquest.ConquestTabs
import ru.glassspirit.eclipsis.kotlin.setModCreativeTab
import ru.glassspirit.eclipsis.objects.block.BlockModGlass
import ru.glassspirit.eclipsis.objects.block.BlockModHalf
import ru.glassspirit.eclipsis.objects.block.BlockModPlate
import ru.glassspirit.eclipsis.objects.block.BlockModStandartLeaves
import ru.glassspirit.eclipsis.objects.block.decorations.BlockDecor

object ConquestBlocksFull {
    init {
        BlockMod("gravel_full_1_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("gravel_full_1_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("gravel_full_1_charlie", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("gravel_full_1_delta", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("gravel_full_1_echo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("gravel_full_1_fox", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("gravel_full_1_golf", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("gravel_full_1_hotel", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("gravel_full_1_india", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("gravel_full_1_juliet", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)

        BlockMod("ground_full_1_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_1_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_1_charlie", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_1_delta", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_1_echo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_1_fox", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_1_golf", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_1_hotel", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_1_india", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_1_juliet", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_1_kilo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_1_lima", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_1_mike", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_1_november", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_2_charlie", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_2_delta", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_2_echo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_2_golf", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_2_hotel", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_2_india", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_2_juliet", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_2_kilo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_2_mike", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_2_november", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_2_oscar", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_3_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_3_delta", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_3_echo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("ground_full_3_fox", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)

        BlockMod("ground_full_3_golf", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("ground_full_3_hotel", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockMod("iron_full_1_alpha", Material.IRON).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("iron_full_1_bravo", Material.IRON).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("iron_full_1_delta", Material.IRON).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModStandartLeaves("leaves_full_1_alpha").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_1_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_1_charlie").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_1_delta").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_2_alpha").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_2_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_2_charlie").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_2_delta").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_3_alpha").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_3_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_3_charlie").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_3_delta").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_4_alpha").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_4_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_4_charlie").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_4_delta").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_5_alpha").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_5_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_5_charlie").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_5_delta").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_6_alpha").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_6_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_6_charlie").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_6_delta").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_7_alpha").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_7_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_8_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_8_charlie").setModCreativeTab(ConquestTabs.ConquestPlantsTab)

        BlockMod("sand_full_1_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("sand_full_1_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("sand_full_1_charlie", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("sand_full_1_delta", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("sand_full_1_echo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("sand_full_1_fox", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("sand_full_1_golf", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("sand_full_1_hotel", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)

        BlockMod("stone_full_1_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_1_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_1_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_1_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_1_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_1_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_1_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_1_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_1_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_1_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_1_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_1_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_1_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_2_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_2_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_2_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_2_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_2_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_2_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_2_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_2_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_2_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_3_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_4_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_4_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_4_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_4_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_4_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_4_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_4_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_4_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_4_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_4_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_4_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_4_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_5_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_5_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_6_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_6_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_6_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_6_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_6_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_6_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_6_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_6_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_6_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_6_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_6_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_6_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_8_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_8_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_8_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_8_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_8_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_8_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_8_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_8_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_8_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_8_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_8_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_10_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_10_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_10_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_10_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_10_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_10_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_10_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_10_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_10_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_11_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_11_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_11_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_11_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_11_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_11_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_11_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_12_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_12_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_12_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_12_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_12_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_12_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_12_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_12_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_13_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_13_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_13_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)

        BlockMod("stone_full_13_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("stone_full_13_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("stone_full_13_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("stone_full_13_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("stone_full_13_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("stone_full_13_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("stone_full_13_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockMod("stone_full_14_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_14_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_14_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)

        BlockMod("stone_full_14_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_14_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_14_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_14_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_14_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_14_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_14_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_14_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_15_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)

        BlockMod("stone_full_15_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_15_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_15_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_15_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_15_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_15_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_16_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_16_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_16_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_16_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_16_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_16_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_16_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_16_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)

        BlockMod("stone_full_17_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_17_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_17_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_17_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)

        BlockMod("stone_full_17_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_17_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_17_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_18_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_18_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_18_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_18_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_18_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_18_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_19_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_19_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_19_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_19_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_19_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_19_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_19_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_19_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_20_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_20_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_20_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_20_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_20_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_21_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_21_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_21_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_21_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_21_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_21_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_21_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_21_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_21_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_21_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_21_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_21_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_21_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_21_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_21_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_22_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_23_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_23_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_23_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_23_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_23_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_23_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_23_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_23_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_23_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_23_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_23_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_24_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_24_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_24_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_24_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_24_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_24_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_24_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_24_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_24_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_24_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_25_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_25_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_25_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_25_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_25_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_25_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_25_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_25_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_25_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_25_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_25_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_25_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_26_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_26_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_26_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_26_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_26_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_26_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_26_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_26_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_26_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_26_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_27_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_27_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_27_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_27_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_27_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_27_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_27_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_27_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_27_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_27_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_27_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_27_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_27_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_27_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_28_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_29_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockMod("stone_full_30_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)

        BlockMod("stone_full_hard2_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard2_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard2_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard2_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard2_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard2_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard2_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard2_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard2_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard2_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard2_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard3_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard3_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard4_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard4_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard4_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard4_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard4_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard4_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard4_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard4_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard4_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard5_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard5_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard5_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard5_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard5_echo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard5_fox", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard5_golf", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard5_hotel", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockMod("stone_full_hard5_india", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestTopographyTab)

        BlockModPlanks("wood_full_1_alpha").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_bravo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_charlie").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_delta").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_echo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_fox").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_golf").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_hotel").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_india").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_juliet").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_kilo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_lima").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_mike").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_november").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_oscar").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_papa").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_alpha").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_bravo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_charlie").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_delta").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_echo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_fox").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_golf").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_hotel").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_india").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_juliet").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_kilo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_lima").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_november").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_papa").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_alpha").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_bravo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_charlie").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_delta").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_echo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_fox").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_golf").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_hotel").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_india").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_juliet").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_kilo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_lima").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_mike").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_november").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_oscar").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_papa").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_alpha").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_bravo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_charlie").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_delta").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_echo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_fox").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_golf").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_hotel").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)

        BlockMod("wood_full_4_india", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_4_juliet", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_4_kilo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_4_lima", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_4_mike", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_4_november", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_4_oscar", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_4_papa", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)

        BlockModPlanks("wood_full_5_kilo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)

        BlockMod("wood_full_5_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_5_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_5_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_5_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_5_echo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_5_fox", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_5_golf", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_5_hotel", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_5_india", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_5_juliet", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_5_lima", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_5_mike", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_5_november", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_5_oscar", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_5_papa", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_6_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_6_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_6_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_6_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_6_echo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_6_fox", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_6_golf", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_6_hotel", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)

        BlockModPlanks("wood_full_6_india").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_6_juliet").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_6_kilo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_6_lima").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)

        BlockModPlanks("wood_full_6_november").setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModPlanks("wood_full_6_oscar").setModCreativeTab(ConquestTabs.ConquestFurnitureTab)

        BlockMod("wood_full_7_fox", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_7_golf", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_7_hotel", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockMod("wood_full_7_india", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockDecor("wood_fullpartial_2_alpha", Material.WOOD, cutout = true).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockDecor("wood_fullpartial_2_bravo", Material.WOOD, cutout = true).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)

        BlockModPlanks("wood_full_6_papa").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_alpha").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_bravo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_charlie").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_delta").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_echo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_juliet").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_kilo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_lima").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_mike").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_november").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_oscar").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_papa").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_alpha").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_bravo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_delta").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_echo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_fox").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_golf").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_hotel").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_india").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_juliet").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_kilo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_lima").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_mike").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_november").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_oscar").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_papa").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_9_alpha").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_9_bravo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)

        BlockModGlass("glass_glass_1_alpha", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_1_bravo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_1_charlie", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_1_delta", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_1_echo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_1_fox", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_1_golf", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_delta", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_echo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_fox", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_golf", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_hotel", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_india", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_juliet", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_kilo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_lima", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_mike", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_alpha", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_bravo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_charlie", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_delta", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_echo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_fox", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_golf", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_hotel", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_india", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_juliet", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_kilo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_lima", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_mike", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_november", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_oscar", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_papa", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_4_alpha", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_4_bravo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_4_charlie", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_4_delta", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_4_india", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModPillar("plants_log_1_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPillar("plants_log_1_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPillar("plants_log_1_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPillar("plants_log_1_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPillar("plants_log_2_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPillar("plants_log_2_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModPillar("stone_log_1_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModPillar("stone_log_1_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModPillar("stone_log_1_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModPillar("stone_log_2_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModPillar("stone_log_2_charlie", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModPillar("stone_log_2_delta", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModPillar("stone_log_3_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)

        BlockModPillar("wood_log_1_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_1_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_1_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_1_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_10_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_10_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_10_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_2_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_2_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_2_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_2_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_3_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_3_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_3_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_3_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_4_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_4_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_4_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_4_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_5_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_5_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_5_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_5_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_6_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_6_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_6_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_6_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_7_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_7_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_7_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_7_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_8_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_8_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_8_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_8_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_9_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_9_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_9_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_9_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)

        BlockModHalf("wood_half_1_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModHalf("wood_half_1_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModHalf("wood_half_1_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModHalf("wood_half_1_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModHalf("wood_half_1_echo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModHalf("wood_half_1_fox", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModHalf("wood_half_1_golf", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModHalf("wood_half_1_hotel", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModHalf("wood_half_1_india", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModHalf("wood_half_1_juliet", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)

        BlockModPlate("wood_daylightdetector_1_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModPlate("wood_daylightdetector_1_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModPlate("wood_daylightdetector_1_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModPlate("wood_daylightdetector_1_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModPlate("wood_daylightdetector_1_echo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModPlate("wood_daylightdetector_1_fox", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModPlate("wood_daylightdetector_1_golf", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModPlate("wood_daylightdetector_1_hotel", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockModPlate("wood_daylightdetector_1_india", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
    }
}