package ru.glassspirit.conquest.block

import com.teamwizardry.librarianlib.features.base.block.BlockModPane
import net.minecraft.block.material.Material
import net.minecraft.creativetab.CreativeTabs
import net.minecraft.init.Blocks
import ru.glassspirit.conquest.ConquestTabs
import ru.glassspirit.eclipsis.kotlin.setModCreativeTab
import ru.glassspirit.eclipsis.objects.block.BlockModFullNoCollision
import ru.glassspirit.eclipsis.objects.block.BlockModPlate
import ru.glassspirit.eclipsis.objects.block.BlockModRail
import ru.glassspirit.eclipsis.objects.block.decorations.*

object ConquestBlocksNoCollision {
    init {
        BlockDecorPlate("cloth_nocollision_1_alpha", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorPlate("cloth_nocollision_1_bravo", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorPlate("cloth_nocollision_1_echo", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorPlate("cloth_nocollision_1_golf", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorPlate("cloth_nocollision_1_hotel", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorPlate("cloth_nocollision_1_india", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorPlate("nomaterial_nocollision_cowpatty", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorPlate("stone_nocollision_1_alpha", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorPlate("stone_nocollision_1_kilo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorPlate("stone_nocollision_2_echo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorPlate("stone_nocollision_2_fox", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorPlate("stone_nocollision_3_echo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorPlate("wood_nocollision_1_alpha", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorPlate("wood_nocollision_1_bravo", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorPlate("wood_nocollision_1_charlie", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorPlate("wood_nocollision_1_hotel", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFlowerPot("ice_nocollision_1_bravo", Material.ICE).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFlowerPot("ice_nocollision_1_charlie", Material.ICE).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFlowerPot("ice_nocollision_1_delta", Material.ICE).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockModFullNoCollision("cloth_nocollision_1_fox", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("cloth_nocollision_1_juliet", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("cloth_nocollision_1_kilo", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("cloth_nocollision_birdnest_1", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("cloth_nocollision_birdnest_2", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockModFullNoCollision("ice_nocollision_1_alpha", Material.ICE).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockModFullNoCollision("nomaterial_nocollision_1_alpha", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_1_bravo", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_1_charlie", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_1_delta", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_1_echo", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_1_fox", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_1_golf", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_1_hotel", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_1_india", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_1_juliet", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_1_lima", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_1_mike", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_flies", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_butterfly_orange", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_butterfly_blue", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_dragonfly", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_hanging_1", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_hanging_2", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_hanging_3", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_hanging_4", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_hanging_5", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_hanging_6", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_hanging_7", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_hanging_8", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_hanging_9", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_hanging_10", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("nomaterial_nocollision_hanging_11", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorSapling("plants_nocollision_1_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorSapling("plants_nocollision_1_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorSapling("plants_nocollision_1_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorSapling("plants_nocollision_1_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorSapling("plants_nocollision_1_echo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorSapling("plants_nocollision_1_fox", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_1_hotel", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_2_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_2_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_2_echo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_2_fox", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_2_golf", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_2_hotel", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_2_india", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_2_juliet", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_2_kilo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_2_lima", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_2_mike", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_2_november", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_2_oscar", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_3_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_3_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_3_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_3_fox", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_3_india", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_3_kilo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_3_lima", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_3_mike", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_4_juliet", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_4_kilo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_4_lima", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_4_mike", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_4_november", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_4_papa", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_5_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_5_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_5_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_5_fox", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_5_lima", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_5_mike", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorBush("plants_nocollision_1_golf", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorBush("plants_nocollision_5_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorBush("plants_nocollision_3_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorBush("plants_nocollision_3_echo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModPlate("plants_lilypad_1_normal", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModPlate("plants_lilypad_2_normal", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollisionbiome_1_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollisionbiome_1_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollisionbiome_1_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModPane("plants_nocollisionconnectedxz_1_alpha", true, Blocks.WOOL.defaultState).setModCreativeTab(ConquestTabs.ConquestPlantsTab)

        BlockModFullNoCollision("plants_nocollision_6_alpha", Material.PLANTS).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("plants_nocollision_6_bravo", Material.PLANTS).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorPlate("plants_nocollision_6_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)

        BlockModFullNoCollision("plants_nocollision_7_charlie", Material.PLANTS).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("plants_nocollision_7_delta", Material.PLANTS).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("plants_nocollision_7_echo", Material.PLANTS).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("plants_nocollision_7_fox", Material.PLANTS).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockModFullNoCollision("plants_nocollision_7_india", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_7_juliet", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_7_kilo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_8_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_8_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_8_hotel", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_8_india", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_8_kilo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_8_lima", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_8_mike", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_8_oscar", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorPlate("plants_nocollision_8_papa", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_9_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorPlate("plants_nocollision_9_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_9_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_9_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_9_fox", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_9_hotel", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorPlate("plants_nocollision_9_india", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_9_juliet", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_9_lima", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_9_mike", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_9_november", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_9_papa", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_10_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_10_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_10_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_10_echo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_10_hotel", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_10_india", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_10_juliet", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_10_kilo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_10_lima", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_10_mike", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_10_november", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_10_oscar", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_10_papa", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_11_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_11_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_11_echo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_11_fox", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_11_golf", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModFullNoCollision("plants_nocollision_11_india", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)

        BlockModFullNoCollision("stone_nocollision_1_bravo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("stone_nocollision_1_charlie", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("stone_nocollision_1_fox", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("stone_nocollision_1_golf", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorRope("stone_nocollision_1_lima", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorRope("stone_nocollision_1_mike", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorRope("stone_nocollision_1_november", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorRope("stone_nocollision_1_oscar", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModRail("rail_cloth").setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModRail("rail_ironchain").setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("stone_nocollision_1_papa", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("stone_nocollision_2_alpha", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFlowerPot("stone_nocollision_2_golf", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFlowerPot("stone_nocollision_2_hotel", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFlowerPot("stone_nocollision_2_india", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("stone_nocollision_2_juliet", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("stone_nocollision_3_bravo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorBush("stone_nocollision_3_golf", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorBush("stone_nocollision_3_hotel", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorBush("stone_nocollision_3_india", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("stone_nocollision_3_juliet", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("stone_nocollision_4_bravo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("stone_nocollision_4_charlie", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockModFullNoCollision("wood_nocollision_1_delta", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("wood_nocollision_1_echo", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModFullNoCollision("wood_nocollision_1_fox", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFlowerPot("wood_nocollision_1_golf", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorDirectionalPassable("cloth_directionalnocollision_1_alpha", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalPassable("cloth_directionalnocollision_1_bravo", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalPassable("cloth_directionalnocollision_1_charlie", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalPassable("iron_directionalnocollision_1_alpha", Material.IRON).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalPassable("iron_directionalnocollision_1_bravo", Material.IRON).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalPassable("iron_directionalnocollision_1_charlie", Material.IRON).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalPassable("iron_directionalnocollision_1_delta", Material.IRON).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalPassable("iron_directionalnocollision_2_alpha", Material.IRON).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalPassable("iron_directionalnocollision_2_bravo", Material.IRON).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalPassable("wood_directionalnocollision_1_alpha", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalPassable("wood_directionalnocollision_1_bravo", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalPassable("wood_directionalnocollision_1_charlie", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalPassable("wood_directionalnocollision_1_delta", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalPassable("wood_directionalnocollision_2_alpha", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalPassable("wood_directionalnocollision_2_bravo", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorDirectional("wood_hopperdirectional_10_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockDecorDirectional("wood_hopperdirectional_8_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockDecorDirectionalPassable("wood_hopperdirectional_8_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockDecorDirectionalPassable("wood_hopperdirectional_8_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestFurnitureTab)
        BlockDecorDirectionalPassable("wood_hopperdirectional_8_delta", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
    }
}