package ru.glassspirit.conquest.block

import net.minecraft.block.material.Material
import ru.glassspirit.conquest.ConquestTabs
import ru.glassspirit.eclipsis.kotlin.setModCreativeTab
import ru.glassspirit.eclipsis.objects.block.BlockModLayer

object ConquestBlocksLayers {
    init {
        BlockModLayer("grass_layer_1_alpha", Material.GRASS).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("grass_layer_1_bravo", Material.GRASS).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_1_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_1_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_2_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_2_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_3_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_3_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_4_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_4_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_5_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_5_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_6_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_6_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_7_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_7_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_8_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_8_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_9_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_9_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_10_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_10_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_11_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_11_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_12_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_12_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_13_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_13_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_14_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_14_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_15_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_15_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_16_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_16_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_17_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_17_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_18_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_18_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_19_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_19_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_20_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_20_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_21_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_21_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_22_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_22_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_23_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_23_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_24_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_24_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("ground_layer_25_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)

        BlockModLayer("ground_layer_25_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("ground_layer_26_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModLayer("ground_layer_26_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)

        BlockModLayer("sand_layer_1_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("sand_layer_1_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("sand_layer_2_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("sand_layer_2_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("sand_layer_3_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("sand_layer_3_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("sand_layer_4_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("sand_layer_4_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("sand_layer_5_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("sand_layer_5_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)
        BlockModLayer("sand_layer_6_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestTopographyTab)

        BlockModLayer("sand_layer_7_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_7_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_8_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_8_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_9_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_9_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_10_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_10_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_11_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_11_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_12_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_12_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_13_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_13_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_14_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_14_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("stone_layer_9_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModLayer("stone_layerdamagelight6_1", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("stone_layerdamagelight8_1", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModLayer("stone_layer_1_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModLayer("stone_layer_1_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModLayer("stone_layer_2_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModLayer("stone_layer_2_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModLayer("stone_layer_3_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModLayer("stone_layer_3_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModLayer("stone_layer_4_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModLayer("stone_layer_4_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModLayer("stone_layer_5_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModLayer("stone_layer_5_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModLayer("stone_layer_6_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModLayer("stone_layer_6_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)

        BlockModLayer("stone_layer_7_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("stone_layer_7_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("stone_layer_8_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModLayer("stone_layer_8_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModLayer("stone_layer_9_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
        BlockModLayer("stone_layer_10_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingStoneTab)
    }
}