package ru.glassspirit.conquest.block

import com.teamwizardry.librarianlib.features.base.block.*
import net.minecraft.block.material.Material
import net.minecraft.init.Blocks
import ru.glassspirit.conquest.ConquestTabs
import ru.glassspirit.eclipsis.kotlin.setModCreativeTab
import ru.glassspirit.eclipsis.objects.block.BlockModGlass
import ru.glassspirit.eclipsis.objects.block.BlockModLayer

object ConquestBuildingOther {
    init {
        BlockMod("ground_full_3_golf", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("ground_full_3_hotel", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("iron_full_1_alpha", Material.IRON).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("iron_full_1_bravo", Material.IRON).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("iron_full_1_delta", Material.IRON).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("stone_full_13_juliet", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("stone_full_13_kilo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("stone_full_13_lima", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("stone_full_13_mike", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("stone_full_13_november", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("stone_full_13_oscar", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockMod("stone_full_13_papa", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModGlass("glass_glass_1_alpha", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_1_bravo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_1_charlie", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_1_delta", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_1_echo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_1_fox", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_1_golf", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_delta", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_echo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_fox", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_golf", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_hotel", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_india", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_juliet", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_kilo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_lima", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_2_mike", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_alpha", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_bravo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_charlie", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_delta", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_echo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_fox", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_golf", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_hotel", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_india", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_juliet", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_kilo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_lima", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_mike", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_november", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_oscar", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_3_papa", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_4_alpha", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_4_bravo", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_4_charlie", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_4_delta", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModGlass("glass_glass_4_india", Material.GLASS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModPillar("plants_log_1_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPillar("plants_log_1_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPillar("plants_log_1_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPillar("plants_log_1_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPillar("plants_log_2_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPillar("plants_log_2_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModSlab("plants_slab_1_alpha", Blocks.TALLGRASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModSlab("plants_slab_1_bravo", Blocks.TALLGRASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModSlab("stone_slab_13_charlie", Blocks.STONE.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModStairs("iron_stairs_1_alpha", Blocks.IRON_BLOCK.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModStairs("iron_stairs_1_bravo", Blocks.IRON_BLOCK.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModStairs("snow_stairs_1_alpha", Blocks.SNOW.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModPane("cloth_pane_1_charlie", true, Blocks.WOOL.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_alpha", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_bravo", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_charlie", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_delta", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_echo", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_fox", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_golf", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_hotel", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_india", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_juliet", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_kilo", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_lima", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_mike", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_november", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_oscar", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_1_papa", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_2_bravo", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_2_charlie", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_2_delta", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_2_echo", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_2_fox", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_2_golf", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_2_hotel", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_2_india", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_alpha", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_bravo", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_charlie", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_delta", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_echo", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_fox", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_golf", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_hotel", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_india", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_juliet", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_kilo", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_lima", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_mike", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_november", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_oscar", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_3_papa", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_4_alpha", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_4_bravo", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_4_charlie", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_4_delta", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("glass_pane_4_echo", true, Blocks.GLASS.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModPane("iron_ironbar_1_bravo", true, Blocks.IRON_BLOCK.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("iron_ironbar_1_charlie", true, Blocks.IRON_BLOCK.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("iron_ironbar_1_delta", true, Blocks.IRON_BLOCK.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("iron_ironbar_1_echo", true, Blocks.IRON_BLOCK.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("iron_ironbar_1_fox", true, Blocks.IRON_BLOCK.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModPane("iron_ironbar_1_india", true, Blocks.IRON_BLOCK.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModLayer("ground_layer_25_bravo", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("ground_layer_26_alpha", Material.GROUND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModLayer("sand_layer_7_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_7_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_8_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_8_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_9_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_9_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_10_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_10_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_11_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_11_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_12_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_12_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_13_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_13_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_14_alpha", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("sand_layer_14_bravo", Material.SAND).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("stone_layer_9_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModLayer("stone_layerdamagelight6_1", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("stone_layerdamagelight8_1", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)

        BlockModLayer("stone_layer_7_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("stone_layer_7_bravo", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
        BlockModLayer("stone_layer_8_alpha", Material.ROCK).setModCreativeTab(ConquestTabs.ConquestBuildingOtherTab)
    }
}