package ru.glassspirit.conquest.block

import net.minecraft.block.material.Material
import ru.glassspirit.conquest.ConquestTabs
import ru.glassspirit.eclipsis.kotlin.setModCreativeTab
import ru.glassspirit.eclipsis.objects.block.BlockDecor
import ru.glassspirit.eclipsis.objects.block.BlockModStandartLeaves
import ru.glassspirit.eclipsis.objects.block.decorations.BlockDecorBush
import ru.glassspirit.eclipsis.objects.block.decorations.BlockDecorCarpet
import ru.glassspirit.eclipsis.objects.block.decorations.BlockDecorFullNoCollision
import ru.glassspirit.eclipsis.objects.block.decorations.BlockDecorSapling

object ConquestPlants {
    init {
        BlockModStandartLeaves("leaves_full_1_alpha").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_1_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_1_charlie").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_1_delta").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_2_alpha").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_2_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_2_charlie").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_2_delta").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_3_alpha").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_3_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_3_charlie").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_3_delta").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_4_alpha").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_4_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_4_charlie").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_4_delta").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_5_alpha").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_5_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_5_charlie").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_5_delta").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_6_alpha").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_6_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_6_charlie").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_6_delta").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_7_alpha").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_7_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_8_bravo").setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockModStandartLeaves("leaves_full_8_charlie").setModCreativeTab(ConquestTabs.ConquestPlantsTab)

        BlockDecorSapling("plants_nocollision_1_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorSapling("plants_nocollision_1_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorSapling("plants_nocollision_1_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorSapling("plants_nocollision_1_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorSapling("plants_nocollision_1_echo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorSapling("plants_nocollision_1_fox", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_1_hotel", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_2_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_2_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_2_echo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_2_fox", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_2_golf", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_2_hotel", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_2_india", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_2_juliet", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_2_kilo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_2_lima", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_2_mike", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_2_november", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_2_oscar", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_3_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_3_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_3_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_3_fox", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_3_india", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_3_kilo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_3_lima", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_3_mike", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_4_juliet", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_4_kilo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_4_lima", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_4_mike", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_4_november", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_4_papa", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_5_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_5_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_5_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_5_fox", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_5_lima", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_5_mike", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorBush("plants_nocollision_1_golf", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorBush("plants_nocollision_5_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorBush("plants_nocollision_3_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorBush("plants_nocollision_3_echo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollisionbiome_1_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollisionbiome_1_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollisionbiome_1_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorCarpet("plants_nocollision_6_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_7_india", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_7_juliet", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_7_kilo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_8_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_8_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_8_hotel", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_8_india", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_8_kilo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_8_lima", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_8_mike", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_8_oscar", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorCarpet("plants_nocollision_8_papa", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_9_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorCarpet("plants_nocollision_9_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_9_charlie", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_9_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_9_fox", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_9_hotel", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorCarpet("plants_nocollision_9_india", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_9_juliet", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_9_lima", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_9_mike", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_9_november", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_9_papa", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_10_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_10_bravo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_10_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_10_echo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_10_hotel", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_10_india", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_10_juliet", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_10_kilo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_10_lima", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_10_mike", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_10_november", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_10_oscar", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_10_papa", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_11_alpha", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_11_delta", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_11_echo", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_11_fox", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_11_golf", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
        BlockDecorFullNoCollision("plants_nocollision_11_india", Material.PLANTS).setModCreativeTab(ConquestTabs.ConquestPlantsTab)

        BlockDecor("wood_fullpartial_1_charlie", Material.WOOD, cutout = true).setModCreativeTab(ConquestTabs.ConquestPlantsTab)
    }
}