package ru.glassspirit.conquest.block

import com.teamwizardry.librarianlib.features.base.block.*
import net.minecraft.block.material.Material
import net.minecraft.init.Blocks
import ru.glassspirit.conquest.ConquestTabs
import ru.glassspirit.eclipsis.kotlin.setModCreativeTab

object ConquestBuildingWood {
    init {
        BlockModPlanks("wood_full_1_alpha").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_bravo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_charlie").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_delta").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_echo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_fox").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_golf").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_hotel").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_india").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_juliet").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_kilo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_lima").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_mike").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_november").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_oscar").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_1_papa").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_alpha").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_bravo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_charlie").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_delta").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_echo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_fox").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_golf").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_hotel").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_india").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_juliet").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_kilo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_lima").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_november").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_2_papa").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_alpha").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_bravo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_charlie").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_delta").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_echo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_fox").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_golf").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_hotel").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_india").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_juliet").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_kilo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_lima").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_mike").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_november").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_oscar").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_3_papa").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_alpha").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_bravo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_charlie").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_delta").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_echo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_fox").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_golf").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_4_hotel").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_5_kilo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_6_india").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_6_juliet").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_6_kilo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_6_lima").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_6_papa").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_alpha").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_bravo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_charlie").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_delta").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_echo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_juliet").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_kilo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_lima").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_mike").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_november").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_oscar").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_7_papa").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_alpha").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_bravo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_delta").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_echo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_fox").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_golf").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_hotel").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_india").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_juliet").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_kilo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_lima").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_mike").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_november").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_oscar").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_8_papa").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_9_alpha").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPlanks("wood_full_9_bravo").setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)

        BlockModPillar("wood_log_1_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_1_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_1_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_1_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_10_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_10_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_10_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_2_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_2_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_2_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_2_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_3_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_3_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_3_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_3_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_4_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_4_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_4_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_4_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_5_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_5_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_5_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_5_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_6_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_6_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_6_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_6_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_7_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_7_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_7_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_7_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_8_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_8_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_8_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_8_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_9_alpha", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_9_bravo", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_9_charlie", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModPillar("wood_log_9_delta", Material.WOOD).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)

        BlockModSlab("wood_slab_1_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_1_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_1_charlie", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_1_echo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_1_fox", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_1_golf", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_1_hotel", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_2_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_2_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_2_charlie", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_2_delta", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_2_echo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_2_fox", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_2_golf", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_2_hotel", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_3_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_3_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_3_charlie", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_3_delta", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_3_echo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_3_fox", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_3_golf", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_3_hotel", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_4_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_4_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_4_charlie", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_4_delta", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_4_echo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_4_fox", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_4_golf", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_4_hotel", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_5_hotel", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_6_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_6_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_6_charlie", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_6_delta", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_6_echo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_6_fox", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_6_golf", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_6_hotel", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_7_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_7_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_7_charlie", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_7_hotel", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_8_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_8_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_8_charlie", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_8_delta", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_8_echo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_8_fox", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_8_hotel", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_9_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_9_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_9_charlie", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_9_delta", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_9_echo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_9_fox", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_9_golf", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_9_hotel", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_10_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_10_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_10_charlie", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_10_delta", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_10_echo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_10_fox", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_10_golf", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_10_hotel", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_11_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_11_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_11_charlie", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_11_delta", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_11_echo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_11_fox", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModSlab("wood_slab_11_golf", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)

        BlockModStairs("wood_stairs_6_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_7_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_8_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_12_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_13_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_13_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_14_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_14_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_15_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_15_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_16_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_16_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_17_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_17_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_18_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_18_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_19_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_19_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_20_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_20_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_24_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_25_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_25_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_26_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_26_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_27_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_28_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_29_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_29_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_30_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_31_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_31_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_32_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_32_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_33_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_33_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_34_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_40_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_40_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_42_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModStairs("wood_stairs_42_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)

        BlockModFence("wood_fence_1_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_1_hotel", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_1_india", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_1_juliet", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_2_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_2_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_2_charlie", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_2_delta", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_2_echo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_2_golf", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_2_hotel", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_2_india", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_2_juliet", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_2_kilo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_2_lima", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_2_mike", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_3_charlie", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_3_delta", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_3_echo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_3_fox", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_3_golf", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_3_hotel", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_3_india", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_3_juliet", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_3_november", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_3_oscar", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_3_papa", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_4_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_4_charlie", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_4_delta", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_4_echo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_4_fox", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_4_golf", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_4_hotel", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_4_india", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_4_juliet", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_4_kilo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_4_lima", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_4_mike", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_4_november", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_4_oscar", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_4_papa", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_5_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_5_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_5_charlie", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_5_delta", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_5_echo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModFence("wood_fence_5_fox", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)

        BlockModWall("wood_wall_5_echo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_5_papa", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_alpha", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_bravo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_charlie", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_delta", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_echo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_fox", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_golf", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_hotel", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_india", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_juliet", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_kilo", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_lima", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_mike", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_november", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_oscar", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
        BlockModWall("wood_wall_6_papa", Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)

        BlockModPane("wood_ironbar_1_alpha", true, Blocks.LOG.defaultState).setModCreativeTab(ConquestTabs.ConquestBuildingWoodTab)
    }
}