package ru.glassspirit.conquest.block

import com.teamwizardry.librarianlib.features.base.block.BlockModPane
import net.minecraft.block.material.Material
import net.minecraft.creativetab.CreativeTabs
import net.minecraft.init.Blocks
import ru.glassspirit.eclipsis.kotlin.setModCreativeTab
import ru.glassspirit.eclipsis.objects.block.BlockDecor
import ru.glassspirit.eclipsis.objects.block.BlockModHalf
import ru.glassspirit.eclipsis.objects.block.BlockModRail
import ru.glassspirit.eclipsis.objects.block.decorations.*

object ConquestDecorations {
    init {
        BlockDecorCarpet("stone_carpet_1_echo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_1_fox", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_1_golf", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_1_lima", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_1_mike", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_1_november", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_1_papa", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_2_alpha", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_3_lima", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_3_mike", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_3_november", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_3_oscar", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_3_papa", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_4_alpha", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_4_bravo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_4_charlie", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_4_delta", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_4_echo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_4_fox", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_4_golf", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_4_hotel", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_4_india", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_carpet_4_juliet", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorCarpet("cloth_nocollision_1_alpha", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("cloth_nocollision_1_bravo", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("cloth_nocollision_1_echo", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("cloth_nocollision_1_golf", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("cloth_nocollision_1_hotel", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("cloth_nocollision_1_india", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorCarpet("nomaterial_nocollision_cowpatty", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorCarpet("stone_nocollision_1_alpha", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_nocollision_1_kilo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_nocollision_2_echo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_nocollision_2_fox", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("stone_nocollision_3_echo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorCarpet("wood_nocollision_1_alpha", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("wood_nocollision_1_bravo", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("wood_nocollision_1_charlie", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorCarpet("wood_nocollision_1_hotel", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFlowerPot("ice_nocollision_1_bravo", Material.ICE).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFlowerPot("ice_nocollision_1_charlie", Material.ICE).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFlowerPot("ice_nocollision_1_delta", Material.ICE).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorFullNoCollision("cloth_nocollision_1_fox", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("cloth_nocollision_1_juliet", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("cloth_nocollision_1_kilo", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("cloth_nocollision_birdnest_1", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("cloth_nocollision_birdnest_2", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorFullNoCollision("ice_nocollision_1_alpha", Material.ICE).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorFullNoCollision("nomaterial_nocollision_1_alpha", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_1_bravo", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_1_charlie", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_1_delta", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_1_echo", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_1_fox", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_1_golf", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_1_hotel", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_1_india", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_1_juliet", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_1_lima", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_1_mike", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_flies", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_butterfly_orange", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_butterfly_blue", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_dragonfly", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_hanging_1", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_hanging_2", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_hanging_3", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_hanging_4", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_hanging_5", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_hanging_6", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_hanging_7", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_hanging_8", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_hanging_9", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_hanging_10", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("nomaterial_nocollision_hanging_11", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorFullNoCollision("plants_nocollision_6_alpha", Material.PLANTS).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("plants_nocollision_6_bravo", Material.PLANTS).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorFullNoCollision("plants_nocollision_7_charlie", Material.PLANTS).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("plants_nocollision_7_delta", Material.PLANTS).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("plants_nocollision_7_echo", Material.PLANTS).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("plants_nocollision_7_fox", Material.PLANTS).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorFullNoCollision("stone_nocollision_1_bravo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("stone_nocollision_1_charlie", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("stone_nocollision_1_fox", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("stone_nocollision_1_golf", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorRope("stone_nocollision_1_lima", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorRope("stone_nocollision_1_mike", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorRope("stone_nocollision_1_november", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorRope("stone_nocollision_1_oscar", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModRail("rail_cloth").setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModRail("rail_ironchain").setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("stone_nocollision_1_papa", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("stone_nocollision_2_alpha", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFlowerPot("stone_nocollision_2_golf", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFlowerPot("stone_nocollision_2_hotel", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFlowerPot("stone_nocollision_2_india", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("stone_nocollision_2_juliet", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("stone_nocollision_3_bravo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorBush("stone_nocollision_3_golf", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorBush("stone_nocollision_3_hotel", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorBush("stone_nocollision_3_india", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("stone_nocollision_3_juliet", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorLight("iron_fullpartiallight10_1_alpha", Material.IRON, 1f).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorLight("iron_fullpartiallight10_1_bravo", Material.IRON, 1f).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorLight("iron_fullpartiallight10_1_charlie", Material.IRON, 1f).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorLight("iron_fullpartiallight10_1_echo", Material.IRON, 1f).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorLight("iron_fullpartiallight10_1_fox", Material.IRON, 1f).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorLight("iron_fullpartiallight10_1_golf", Material.IRON, 1f).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorLight("iron_fullpartiallight10_1_hotel", Material.IRON, 1f).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("stone_nocollision_4_bravo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("stone_nocollision_4_charlie", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorFullNoCollision("wood_nocollision_1_delta", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("wood_nocollision_1_echo", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFullNoCollision("wood_nocollision_1_fox", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFlowerPot("wood_nocollision_1_golf", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorDirectionalFullNoCollision("cloth_directionalnocollision_1_alpha", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("cloth_directionalnocollision_1_bravo", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("cloth_directionalnocollision_1_charlie", Material.CLOTH).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("iron_directionalnocollision_1_alpha", Material.IRON).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("iron_directionalnocollision_1_bravo", Material.IRON).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("iron_directionalnocollision_1_charlie", Material.IRON).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("iron_directionalnocollision_1_delta", Material.IRON).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("iron_directionalnocollision_2_alpha", Material.IRON).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("iron_directionalnocollision_2_bravo", Material.IRON).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("wood_directionalnocollision_1_alpha", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("wood_directionalnocollision_1_bravo", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("wood_directionalnocollision_1_charlie", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("wood_directionalnocollision_1_delta", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("wood_directionalnocollision_2_alpha", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("wood_directionalnocollision_2_bravo", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("wood_hopperdirectional_8_delta", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("bellows_alpha", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalFullNoCollision("tanning_rack_alpha", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecor("stone_fullpartial_6_lima", Material.ROCK, cutout = true).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorFlowerPot("stone_fullpartial_7_kilo", Material.ROCK).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecor("wood_fullpartial_1_alpha", Material.WOOD, cutout = true).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockModHalf("wood_fullpartial_1_papa", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorDirectionalLight("torch_10_1_alpha", Material.WOOD, 1f, false).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalLight("torch_10_1_bravo", Material.WOOD, 1f, false).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockDecorDirectionalLight("torch_10_2_alpha", Material.WOOD, 1f, false).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockModPane("cloth_climbironbar_1_alpha", true, Blocks.WOOL.defaultState).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModPane("cloth_climbironbar_1_bravo", true, Blocks.WOOL.defaultState).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModPane("cloth_climbironbar_1_charlie", true, Blocks.WOOL.defaultState).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModPane("cloth_climbironbar_1_delta", true, Blocks.WOOL.defaultState).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModPane("cloth_climbironbar_1_echo", true, Blocks.WOOL.defaultState).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModPane("cloth_climbironbar_1_fox", true, Blocks.WOOL.defaultState).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModPane("cloth_climbironbar_1_golf", true, Blocks.WOOL.defaultState).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModPane("cloth_climbironbar_1_hotel", true, Blocks.WOOL.defaultState).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModPane("cloth_ironclimbironbar_1_alpha", true, Blocks.WOOL.defaultState).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModPane("cloth_ironclimbironbar_1_bravo", true, Blocks.WOOL.defaultState).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModPane("cloth_ironclimbironbar_1_charlie", true, Blocks.WOOL.defaultState).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockModPane("wood_ironbar_1_echo", true, Blocks.LOG.defaultState).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModPane("wood_ironbar_1_fox", true, Blocks.LOG.defaultState).setModCreativeTab(CreativeTabs.DECORATIONS)
        BlockModPane("wood_ironbar_1_golf", true, Blocks.LOG.defaultState).setModCreativeTab(CreativeTabs.DECORATIONS)

        BlockDecorWall("wood_smallpillar_4_delta", Material.WOOD).setModCreativeTab(CreativeTabs.DECORATIONS)
    }
}